# Generated by Django 5.1.4 on 2025-01-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="world",
            name="slug",
            field=models.SlugField(default=" ", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
